name: Update v8 version

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-version:
    permissions: write-all
    name: Update v8 version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.version }}
      version-last: ${{ steps.check.outputs.version-last }}
    steps:
      - uses: actions/checkout@v3
      - name: Check v8 version
        id: check
        run: |
          cd $GITHUB_WORKSPACE
          yarn install
          node ./js/Update_v8_version.js
      - name: Read output
        run: |
          echo $GITHUB_OUTPUT
          echo "version ${{steps.check.outputs.version}}"
          echo "version-last ${{steps.check.outputs.version-last}}"
      - name: Commit & Push changes
        uses: actions-x/commit@v6
        if: ${{ steps.check.outputs.version != steps.check.outputs.version-last }}
        with:
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
          message: Update v8 version

  build:
    name: Dispatch build and release
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Start Builds and Publish Release
        if: ${{ needs.update-version.outputs.version != needs.update-version.outputs.version-last }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Start Builds and Publish Release
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "version": "${{ needs.update-version.outputs.version }}" }'
