name: Start Builds and Publish Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: V8 version to publish
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workflow:
          - Windows Builds
          - Linux Builds
          - Android Builds
<<<<<<< HEAD:.github/workflows/1.2-Start Builds and Publish Release.yml
          - macOS Builds
          - iOS Builds
=======
          - iOS Builds
          - macOS Builds
>>>>>>> c759b8dbbfedf699e2b3fb728db81c4707bea05a:.github/workflows/start-build-publish.yml
          - Publish Release
    steps:
      - name: ${{ matrix.workflow }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ matrix.workflow }}
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: '{ "version": "${{ inputs.version }}" }'
