name: Publish Release
on:
  push:
    tags:
      - '*'
    paths:
      - v8_version
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: V8 version to publish

jobs:
  collect-template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/github-script@v6
      id: download_artifacts
      with:
        script: |-
          const script = require('./js/Download_artifacts.js')
          await script(github, context)
    - name: Show binary files
      run: |
        echo "${{steps.download_artifacts.outputs.result}}"
        ls -R bin
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ inputs.version }}
        release_name: V8 ${{ inputs.version }}
        draft: false
        prerelease: false
    - uses: xresloader/upload-to-github-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "bin/*.zip"
        release_id: ${{ steps.create_release.outputs.id }}
        overwrite: true
        verbose: true