name: Windows Builds
on:
  push: {}
  pull_request: {}
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of V8 to build'
        required: false

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows
  cancel-in-progress: true

env:
  VERSION: ""

jobs:
  build-windows:
    runs-on: windows-latest
    name: Windows ${{ matrix.type }} (${{ matrix.target_cpu }}${{ matrix.crt }})
    strategy:
      fail-fast: false
      matrix:
        target_cpu: [ 'x64', 'x86' ]
        type: [ 'static', 'dynamic' ]
        crt: [ '', 'AMD' ]
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/v8-version
      with:
        version: ${{ github.inputs.version }}
    - name: Run Build Script
      shell: cmd
      run: |
        cd ${{ github.workspace }}
        call .\build.cmd win ${{ matrix.target_cpu }} ${{ matrix.type }} ${{ env.VERSION }} ${{ matrix.crt }}
    - uses: actions/upload-artifact@v2
      with:
        name: Windows-${{matrix.target_cpu}}-${{ matrix.type }}-${{ matrix.crt }}
        path: v8/v8/output/**/*
