name: Linux Builds
on:
  push: {}
  pull_request: {}
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of V8 to build'
        required: false

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-linux
  cancel-in-progress: true

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Linux ${{ matrix.type }} (${{ matrix.target_cpu }})
    strategy:
      fail-fast: false
      matrix:
        target_cpu: [ 'x64' ]
        type: [ 'static', 'dynamic' ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Run Build Script
      run: |
        cd ${{ github.workspace }}
<<<<<<< HEAD:.github/workflows/2.2-Linux Builds.yml
        sh ./build.sh linux ${{ matrix.target_cpu }} ${{ matrix.type }} ${{ inputs.VERSION }}
    - uses: actions/upload-artifact@v3
      with:
        name: v8-Linux-${{matrix.target_cpu}}-${{ matrix.type }}
        path: ~/v8/v8/output/**/*
=======
        sh ./build.sh linux ${{ matrix.target_cpu }} ${{ matrix.type }} ${{ env.VERSION }}
    - uses: actions/upload-artifact@v2
      with:
        name: Linux-${{matrix.target_cpu}}-${{ matrix.type }}
        path: ~/v8/v8/output/**/*
>>>>>>> c759b8dbbfedf699e2b3fb728db81c4707bea05a:.github/workflows/linux.yml
