name: Android Builds
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of V8 to build'
        required: false

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Android ${{ matrix.type }} (${{ matrix.target_cpu }})
    strategy:
      fail-fast: false
      matrix:
        target_cpu: [ 'arm', 'arm64', 'x64' ]
        type: [ 'static', 'dynamic' ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Run Build Script
      run: |
        cd ${{ github.workspace }}
        sh ./build.sh android ${{ matrix.target_cpu }} ${{ matrix.type }} ${{ inputs.VERSION }}
    - uses: actions/upload-artifact@v3
      with:
        name: v8-Android-${{matrix.target_cpu}}-${{ matrix.type }}
        path: ~/v8/v8/output/**/*
